### ISSUE TITLE
Does not work for a simple component

### ISSUE THREAD

**Issue by boris-petrov** [simplabs/ember-hbs-minifier#226]
```sh
ember new hbs-minifier-test
cd hbs-minifier-test
ember install ember-hbs-minifier
echo "{{#if true}}\n      {{log 1}}\n{{/if}}\n{{#if true}}\n    Hi there\n{{/if}}" > app/components/some-component.hbs
ember server
```

Generates:

```javascript
block: "{\"symbols\":[],\"statements\":[[4,\"if\",[true],null,{\"statements\":[[0,\"      \"],[1,[28,\"log\",[1],null],false],[0,\"\\n\"]],\"parameters\":[]},null],[4,\"if\",[true],null,{\"statements\":[[0,\"    Hi there\\n\"]],\"parameters\":[]},null]],\"hasEval\":false}",
```

You can still see the spaces in the generated "machine code". Am I missing something? Isn't this supposed to remove these spaces by default with no configuration?

Happens on both Ember 3.16 and 3.17.

**Comment by Turbo87** [comment]
hmm, that does look strange. the whitespaces should have at least been collapsed to a single space. it almost looks like adding the addon does not have any effect at all. 🤔

**Comment by siva-sundar** [comment]
Registering the plugin inside the `setupPreprocessorRegistry` hook instead of the `included` solved the issue. I am not sure about the reason behind this.

@Turbo87 Do you mind if I raise a PR ?

**Comment by Turbo87** [comment]
> Happens on both Ember 3.16 and 3.17.

@boris-petrov do you mean `ember-cli` 3.16/17, or `ember-source` 3.16/17?

**Comment by boris-petrov** [comment]
@Turbo87 - well, I don't remember (I would guess I was talking about `ember-source`), but here is the result from `ember-cli` 3.17.0 and `ember-source` 3.18.0:

```handlebars
block: "{\"symbols\":[],\"statements\":[[5,[27,[26,1,\"BlockHead\"],[]],[true],null,[[\"default\"],[{\"statements\":[[1,1,0,0,\"      \"],[1,0,0,0,[31,21,3,[27,[26,0,\"CallHead\"],[]],[1],null]],[1,1,0,0,\"\\n\"]],\"parameters\":[]}]]],[5,[27,[26,1,\"BlockHead\"],[]],[true],null,[[\"default\"],[{\"statements\":[[1,1,0,0,\"    Hi there\\n\"]],\"parameters\":[]}]]]],\"hasEval\":false,\"upvars\":[\"log\",\"if\"]}",
```

The plugin still doesn't work.

**Comment by Turbo87** [comment]
@boris-petrov I think the issue is that you were using a colocated component template. https://github.com/simplabs/ember-test-selectors/pull/521 fixed a similar issue for ember-test-selectors and I expect this to be the correct solution here too. Can you verify if that solves the issue for you?

**Comment by boris-petrov** [comment]
@Turbo87 - that does seem to fix the issue, yes!

**Comment by patsy-issa** [comment]
While this seems to have fixed the issue with the ast plugins not being loaded in the correct order it is not removing leading whitespaces in colocated component templates (I have simplified the template):

```javascript
 {
    id: "qBBOrLXg",
    block: "{\"symbols\":[],\"statements\":[[2,\"    Hi there\\n\"]],\"hasEval\":false,\"upvars\":[]}",
    meta: {
      moduleName: "foo/components/some-component.hbs"
    }
  }
```
