### ISSUE TITLE
Discussion: Preserve white space based on a whitelist

### ISSUE THREAD

**Issue by siva-sundar** [simplabs/ember-hbs-minifier#9]
Can we have a white list file with the class and component names mentioned for which we need to preserve the whitespace?

Note: 
In case the component name or the class name can be resolved only at runtime. For instance,

`{{#component componentName}}
     ...
   {{/component}}` 
or 
`<div class={{flightStatus}}> {{flightStatus}} </div>`

Then, we can preserve the whitespace.

**Comment by siva-sundar** [comment]
If its ok.  I can raise a PR.

**Comment by Turbo87** [comment]
Sounds like a good idea to me to make it configurable :+1:

**Comment by Turbo87** [comment]
resolved by #14
